# This is a basic workflow to help you get started with Actions

name: CI-CD

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  CI:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v3
      
      - name: Docker Login
        uses: docker/login-action@v2.0.0
        with:
          username: ${{secrets.DOCKERHUB_USER}}
          password: ${{secrets.DOCKERHUB_PSWD}}
          
      - name: Build and push Docker images
        uses: docker/build-push-action@v3.1.0
        with:
          file: ./src/Dockerfile
          context: ./src
          push: true
          tags: |
            zepolsoft/kube-news:latest
            zepolsoft/kube-news:${{github.run_number}}
  CD:
    runs-on: ubuntu-latest
    needs: [CI]
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v3
      
      - name: Azure Kubernetes set context
        uses: Azure/aks-set-context@v2
        with:
          method: kubeconfig
          kubeconfig: ${{secrets.K8S_CONFIG}}
      
      - name: Deploy to Kubernetes cluster
        uses: Azure/k8s-deploy@v4.3
        with:
          images: zepolsoft/kube-news:${{github.run_number}}
          manifests: |
            k8s/deployment.yaml
